/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TheGameBoard: typeof import('./src/components/TheGameBoard.vue')['default']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
  }
}
